### PR TITLE
[3.0-preview] Update polymer.json for webcomponentsjs changes.

### PR DESCRIPTION
**Pull request by bicknellr**
The polyfill bundles have moved into `/bundles`.

### CODE REVIEW

**Comment by bicknellr** [comment]
Actually, no, this needs to be updated to make sure that the builds include the new location of the webcomponentsjs bundles!

**Comment by abdonrd** [comment]
I think with these we also fix it:
https://github.com/webcomponents/webcomponentsjs/pull/929#issuecomment-387305470

**Comment by bicknellr** [comment]
@abdonrd is that because `polymer build` includes things listed in `files` in your build output?

**Comment by abdonrd** [comment]
@bicknellr no, the idea is reduce the `npm install @webcomponents/webcomponentsjs` output.

You can see the actual output here:
https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0-beta.2/

With https://github.com/webcomponents/webcomponentsjs/pull/929 we reduce the output to only:

```
"bundles/**/*",
"entrypoints/**/*",
"custom-elements-es5-adapter.js",
"webcomponents-bundle.js",
"webcomponents-bundle.js.map",
"webcomponents-loader.js"
```

**Comment by bicknellr** [comment]
Oh, I read "I think with these we also fix it:" and though you were referring to this bug, rather than Keanu's comment about copying more than necessary.

**Comment by abdonrd** [comment]
@bicknellr ops! Sorry for the confusion! 😅

**Pull request merged**
