### PR TITLE
[3.0-preview] Update `README.md`.

### LINKED ISSUE #1099: README.md needs to be updated for Polymer 3
https://github.com/Polymer/polymer-starter-kit/blob/4858f06b3889fcbd27e39f6622b3888cfba0852b/README.md

The links in this document all point to Polymer 2 docs. I think most of the instructions themselves are still ok though.

- [x] What are the Windows-specific environment variables listed at the bottom about?
- [x] Add references to the old docs?

### PR DESCRIPTION
**Pull request by bicknellr**
- [x] Confirm URLs.
- [ ] Add explicit link to older docs with video and blog post links?
- [ ] What is Launchpad? Does this section need updates?

(Fixes #1099.)

### CODE REVIEW

**Comment by bicknellr** [comment]
I'm not sure if we have any specific media to link to about updates to PSK yet. I think once we plan to do a blog post then we could add that then. Mostly I've just changed the links here. Also, does anyone know what this Launchpad section at the bottom is about? Is that a WCT thing?

**Comment by katejeffreys** [comment]
Thanks for this, URLs look good and will be correct when https://github.com/Polymer/docs/pull/2498 and toolbox docs are published.

Also should we change the repo link to the 3.0 app tutorial when it's published? https://github.com/Polymer/docs/pull/2536

The launchpad thing seems to be related to WCT on Windows.. I haven't tried this, idk if it needs updates

**Comment by bicknellr** [comment]
> Also should we change the repo link to the 3.0 app tutorial when it's published?

Which link is this?

**Comment by katejeffreys** [comment]
>Which link is this?

screen shot 2018-04-27 at 6 54 00 pm

**Comment by bicknellr** [comment]
I'm going to ignore the launchpad question for now and merge this.

**Pull request merged**
